version: '3.8'
services:
    dynamodb-local:
        image: amazon/dynamodb-local:1.13.3
        ports:
            - "8000:8000"
    pandora:
        build: .
        image: pandora-build
        container_name: pandora_api
        depends_on:
            - dynamodb-local
        links:
            - "dynamodb-local"
        command: 'bash -c "./load_data.sh && flask run --host 0.0.0.0"'
        volumes:
            - ./resources:/opt/pandora/resources
        environment:
            - AWS_ACCESS_KEY_ID='MY_ACCESS_KEY'
            - AWS_SECRET_ACCESS_KEY='MY_SECRET_KEY'
            - FLASK_APP=/opt/pandora/app/app.py
            - FLASK_ENV=development
        ports:
            - "5000:5000"